import React, { useEffect, useState } from "react";
import Head from "next/head";
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from "react-icons/ai";
import { BsFillMoonStarsFill, BsFillPatchCheckFill } from "react-icons/bs";
import "swiper/swiper-bundle.css";
import deved from "../public/ozi.png";
import ME from "../public/gunung.jpg";
import Image from "next/image";
import AOS from "aos";
import "aos/dist/aos.css";
import exp from "../public/work.jpg";

export default function Home() {


  const portfolioData = [
    {
      image: "/porto3.png",
      title: "Culinarix",
      desc: "Culinarix  merupakan aplikasi rekomendasi kuliner di kota bandung untuk membantu wisatawan ataupun masyarat lokal disana menemukan rekomendasi kuliner yang sesuai dengan preferensi mereka.",
      view: "https://github.com/keeptrain/Culinarix?tab=readme-ov-file",
      demo: "https://www.youtube.com/watch?feature=shared&v=_1JeLwmAOOE",
      techStack: ["Python", "Flask", "Docker", "Firestore", "GCP "]
    },
    {
      image: "/uikit.png",
      title: "UIKIT Website",
      desc: "Website ini merupakan Website Jual Beli UI KIT Figma dengan sistem subscription dengan midtrans.Website ini dibangun menggunakan VueJs 3 dan backend nya menggunakan laravel .                              ",
      view: "https://github.com/alghoziii/FE-UI-KIT",
      techStack: ["VueJs", "JavaScript", "MySQL", "Tailwind", "Laravel"]
    },
    {
      image: "/porto1.png",
      title: "KASIRQ",
      desc: "Mengembangkan sistem kasir berbasis Website (Software as a Service) untuk memudahkan manajemen penjualan toko obat tanaman dan pupuk. Website ini dilengkapi sistem subscription sesuai paket yang dipilih .",
      view: "https://dashboard-kasir.vercel.app/",
      demo: "https://dashboard-kasir.vercel.app/",
      techStack: ["PHP", "MYSQL", "React Js", "Tailwind", "PostgreSQL"]

    },

    {
      image: "/travela.png",
      title: "Travela",
      desc: "Travela Merupakan website booking paket travel secara online yang dibangun menggunakan PHP Laravel 11. Website ini dilengkapi fitur autentikasi pengguna, role-based access control (menggunakan Spatie), content management system untuk admin, checkout dan approval sistem, serta katalog paket tour. ",
      view: "https://github.com/alghoziii/Travela",
      techStack: ["Laravel", " Mysql", "Tailwind", "PHP",]

    },
    {
      image: "/booking.png",
      title: "Mini Soccer Booking",
      desc: "Website pemesanan lapangan mini soccer online yang dibangun dengan arsitektur microservices menggunakan Golang, dilengkapi fitur autentikasi pengguna, cek ketersediaan jadwal lapangan secara real-time,pembayaran online(Midtrans)",
      view: "https://github.com/alghoziii/mini-soccer-booking",
      techStack: ["Golang", " PostgreSql", "Jenkins", "Docker", "GCP", "NEXTJS"]

    },
  ];

  const experiences = [
    {
      period: "Agt 2024 - Jan 2025",
      title: "FULL STACK DEVELOPER",
      company: "Horus Technology(internship)",
      location: "Gamping,Yogyakarta",
      url: "https://www.horus.co.id/",
    },
    {
      period: "Agt 2024 - Jan 2024",
      title: "Cloud Computing",
      company: "Bangkit (Studi Independent)",
      location: "Bandung, Indonesia (Remote)",
      url: "https://grow.google/intl/id_id/bangkit/",
    },
  ];

  useEffect(() => {
    AOS.init({
      duration: 1100,
      once: true,
      mirror: false,
    });

    AOS.refresh();

    return () => {
      AOS.refresh();
    };
  }, []);

  return (
    <div >
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-7xl bg-transparent px-4 text-slate-100 md:px-8 lg:px-12">
        <section className="min-h-screen">
          <nav className="mb-12 flex items-center justify-between py-10">
            <h1 className="font-burtons text-xl text-cyan-100">Portofolio</h1>
            <ul className="flex items-center">
             
              <li>
                <a
                  className="ml-12 rounded-md bg-gradient-to-r from-cyan-500 via-sky-500 to-blue-500 px-8 py-3 text-white shadow-lg shadow-cyan-500/30 transition duration-300 hover:scale-[1.03]"
                  href="/resume.pdf"
                  download="resume.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden md:h-90 md:w-99 bottom-11" data-aos="fade-down">
            <Image src={deved} alt="Hero portrait" layout="fill" objectFit="cover" />
          </div>
          <div className="p-5 py-1 text-center" data-aos="fade-up" data-aos-anchor-placement="center-bottom">
            <h2 className="py-2 text-2xl font-semibold text-cyan-300 md:text-4xl">Shobarudin Alghozi</h2>
            <h3 className="py-3 text-lg text-slate-200 md:text-3md">Fullstack Developer</h3>
          </div>
          <div className="flex justify-center gap-10 py-3 text-slate-400" data-aos="fade-up">
            <a href="https://github.com/alghoziii" target="_blank" rel="noopener noreferrer" className="text-4xl transition-colors duration-300 hover:text-white">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/shobarudin-alghozi-550163217/" target="_blank" rel="noopener noreferrer" className="text-4xl transition-colors duration-300 hover:text-sky-400">
              <AiFillLinkedin />
            </a>
            <a href="https://instagram.com/alghozii_zy" target="_blank" rel="noopener noreferrer" className="text-4xl transition-colors duration-300 hover:text-fuchsia-400">
              <AiFillInstagram />
            </a>
          </div>

        </section>

        <section id="about" className="py-12">
          <h3 className="mb-8 py-1 text-center text-3xl text-cyan-300" data-aos="fade-down">
            About Me
          </h3>

          <div
            className="mx-auto flex max-w-5xl flex-col items-center rounded-3xl border border-cyan-400/20 bg-slate-900/70 p-6 shadow-[0_25px_70px_-35px_rgba(34,211,238,0.75)] backdrop-blur-sm md:flex-row md:p-8"
            data-aos="fade-up"
          >
            <div className="mb-6 w-full md:mb-0 md:mr-8 md:w-2/5">
              <div className="relative aspect-square w-full overflow-hidden rounded-2xl border border-cyan-300/20 shadow-lg shadow-cyan-900/30">
                <Image
                  src={ME}
                  alt="Profile Photo"
                  layout="fill"
                  objectFit="cover"
                  className="rounded-lg transition-transform duration-500 hover:scale-105"
                />
              </div>
            </div>

            <div className="w-full md:w-3/5 max-w-xl flex flex-col">
              <div className="flex-grow">
                <p className="mb-2 max-w-prose px-2 text-justify text-lg leading-relaxed text-slate-200 md:px-0">
                  I&apos;m a passionate web developer specializing in backend development.
                  I have a deep enthusiasm for technology and continuously seek opportunities to expand my knowledge and skills.
                  I thrive in collaborative environments, delivering efficient solutions, and contributing to innovative projects that drive positive change.
                  I am open to diverse job opportunities that align with my expertise and interests.
                </p>
              </div>
            </div>
          </div>
        </section>


        <section id="experience" className="py-12">
          <h3 className="mb-12 py-1 text-center text-3xl font-semibold tracking-wide text-cyan-300" data-aos="fade-down">
            My Journey & Experience
          </h3>

          <div className="mx-auto max-w-5xl relative">
            {/* Timeline line */}
            <div className="absolute left-4 md:left-1/2 ml-0.5 md:ml-0 top-0 bottom-0 w-0.5 bg-gradient-to-b from-cyan-400/80 via-blue-500/50 to-transparent"></div>

            <div className="space-y-12">
              {experiences.map((exp, index) => (
                <div
                  key={index}
                  className={`relative flex flex-col md:flex-row items-center justify-between group ${index % 2 === 0 ? "md:flex-row-reverse" : ""
                    }`}
                  data-aos={index % 2 === 0 ? "fade-left" : "fade-right"}
                >
                  {/* Timeline dot */}
                  <div className="absolute left-4 md:left-1/2 md:transform md:-translate-x-1/2 w-4 h-4 rounded-full bg-cyan-400 border-4 border-slate-900 shadow-[0_0_10px_#22d3ee] z-10 transition-transform duration-300 group-hover:scale-150 group-hover:bg-cyan-300"></div>

                  <div className="w-full md:w-5/12 ml-10 md:ml-0">
                    <a
                      href={exp.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block rounded-2xl border border-cyan-400/20 bg-slate-800/60 p-6 shadow-lg backdrop-blur-sm transition-all duration-300 hover:-translate-y-2 hover:border-cyan-400/60 hover:shadow-[0_15px_40px_-15px_rgba(34,211,238,0.4)]"
                    >
                      <div className="inline-block px-3 py-1 mb-4 text-xs font-semibold tracking-wider text-emerald-400 bg-emerald-400/10 rounded-full border border-emerald-400/20">
                        {exp.period}
                      </div>
                      <h4 className="mb-2 text-2xl font-bold text-white group-hover:text-cyan-300 transition-colors duration-300">
                        {exp.title}
                      </h4>
                      <p className="mb-1 text-lg font-medium text-slate-300">
                        {exp.company}
                      </p>
                      <div className="flex items-center text-sm text-slate-400">
                        <svg className="w-4 h-4 mr-1.5 opacity-70" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.243-4.243a8 8 0 1111.314 0z"></path><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path></svg>
                        {exp.location}
                      </div>

                      <div className="mt-5 flex items-center text-sm font-semibold text-cyan-400 transition-transform duration-300 transform origin-left group-hover:translate-x-2">
                        View Details
                        <svg className="ml-2 w-4 h-4 transition-transform duration-300 group-hover:translate-x-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3"></path></svg>
                      </div>
                    </a>
                  </div>

                  {/* Empty space for the other side of the timeline on desktop */}
                  <div className="hidden md:block w-5/12"></div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section id="skills" className="py-16">
          <h3 className="mb-12 py-1 text-center text-3xl font-semibold tracking-wide text-cyan-300" data-aos="fade-down">
            Tech Arsenal & Skills
          </h3>

          <div className="mx-auto max-w-6xl grid grid-cols-1 md:grid-cols-2 gap-8 px-4" data-aos="zoom-in">
            {/* Frontend Skills */}
            <div className="relative group rounded-3xl border border-cyan-400/20 bg-slate-900/60 p-8 shadow-[0_15px_40px_-20px_rgba(34,211,238,0.3)] backdrop-blur-md transition duration-500 hover:border-cyan-400/50 hover:bg-slate-800/80">
              <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-cyan-500/10 to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100"></div>

              <div className="relative z-10">
                <div className="flex items-center mb-8">
                  <div className="p-3 mr-4 rounded-xl bg-cyan-400/10 text-cyan-400 shadow-[0_0_15px_rgba(34,211,238,0.2)]">
                    <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path></svg>
                  </div>
                  <h3 className="text-2xl font-bold text-white">Frontend</h3>
                </div>

                <div className="grid grid-cols-2 gap-6">
                  {[
                    { name: "Javascript", level: "Intermediate" },
                    { name: "PHP", level: "Intermediate" },
                    { name: "Vue Js", level: "Intermediate" },
                    { name: "Laravel", level: "Intermediate" }
                  ].map((skill, index) => (
                    <div key={index} className="flex flex-col p-4 rounded-2xl bg-slate-800/40 border border-slate-700/50 transition-transform duration-300 hover:-translate-y-1 hover:border-cyan-500/30">
                      <div className="flex items-center mb-2">
                        <BsFillPatchCheckFill className="text-cyan-400 mr-2 text-lg drop-shadow-[0_0_8px_rgba(34,211,238,0.8)]" />
                        <h4 className="font-semibold text-slate-100">{skill.name}</h4>
                      </div>
                      <span className="text-xs font-medium text-slate-400 ml-6">{skill.level}</span>

                      {/* Simple progress bar representation */}
                      <div className="w-full bg-slate-700/50 h-1.5 mt-3 rounded-full overflow-hidden ml-6 max-w-[80%]">
                        <div className="bg-gradient-to-r from-cyan-500 to-blue-500 h-full rounded-full w-[70%]"></div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Backend Skills */}
            <div className="relative group rounded-3xl border border-cyan-400/20 bg-slate-900/60 p-8 shadow-[0_15px_40px_-20px_rgba(34,211,238,0.3)] backdrop-blur-md transition duration-500 hover:border-cyan-400/50 hover:bg-slate-800/80">
              <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-blue-500/10 to-transparent opacity-0 transition-opacity duration-500 group-hover:opacity-100"></div>

              <div className="relative z-10">
                <div className="flex items-center mb-8">
                  <div className="p-3 mr-4 rounded-xl bg-blue-400/10 text-blue-400 shadow-[0_0_15px_rgba(59,130,246,0.2)]">
                    <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"></path></svg>
                  </div>
                  <h3 className="text-2xl font-bold text-white">Backend & Cloud</h3>
                </div>

                <div className="grid grid-cols-2 gap-6">
                  {[
                    { name: "Python", level: "Intermediate", pct: "75%" },
                    { name: "Node JS", level: "Intermediate", pct: "70%" },
                    { name: "Flask", level: "Intermediate", pct: "75%" },
                    { name: "Golang", level: "Pre-intermediate", pct: "50%" },
                    { name: "GCP", level: "Intermediate", pct: "65%" },
                    { name: "SQL DBs", level: "Intermediate", pct: "80%" }
                  ].map((skill, index) => (
                    <div key={index} className="flex flex-col p-4 rounded-2xl bg-slate-800/40 border border-slate-700/50 transition-transform duration-300 hover:-translate-y-1 hover:border-blue-500/30">
                      <div className="flex items-center mb-2">
                        <BsFillPatchCheckFill className="text-blue-400 mr-2 text-lg drop-shadow-[0_0_8px_rgba(59,130,246,0.8)]" />
                        <h4 className="font-semibold text-slate-100">{skill.name}</h4>
                      </div>
                      <span className="text-xs font-medium text-slate-400 ml-6">{skill.level}</span>

                      <div className="w-full bg-slate-700/50 h-1.5 mt-3 rounded-full overflow-hidden ml-6 max-w-[80%]">
                        <div className={`bg-gradient-to-r from-blue-400 to-indigo-500 h-full rounded-full w-[${skill.pct}]`} style={{ width: skill.pct }}></div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="portfolio" className="py-20 relative">
          {/* Subtle background glow */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[600px] bg-cyan-900/20 rounded-full blur-[120px] pointer-events-none"></div>

          <div className="container mx-auto max-w-7xl px-4 relative z-10">
            <div className="text-center mb-16" data-aos="fade-up">
              <h3 className="inline-block py-2 text-4xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">
                Featured Projects
              </h3>
              <p className="mt-4 text-slate-400 max-w-2xl mx-auto">
                A selection of my recent work showcasing my expertise in web development, backend architecture, and creating user-centric solutions.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 xl:gap-10">
              {portfolioData.map((item, index) => (
                <div
                  key={index}
                  className="group flex flex-col h-full overflow-hidden rounded-3xl bg-slate-900/50 border border-slate-700/50 backdrop-blur-sm transition-all duration-500 hover:-translate-y-2 hover:bg-slate-800/80 hover:shadow-[0_20px_40px_-15px_rgba(34,211,238,0.2)] hover:border-cyan-500/30"
                  data-aos="fade-up"
                  data-aos-delay={index * 100}
                >
                  {/* Image Container with Overlay */}
                  <div className="relative h-64 w-full overflow-hidden">
                    <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/20 to-transparent z-10 opacity-60 group-hover:opacity-40 transition-opacity duration-500"></div>
                    <Image
                      src={item.image}
                      alt={item.title}
                      fill
                      sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                      className="object-cover transition-transform duration-700 group-hover:scale-110"
                    />

                    {/* Hover action button */}
                    <div className="absolute inset-0 z-20 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                      <a
                        href={item.view || item.demo || '#'}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="translate-y-4 group-hover:translate-y-0 transition-transform duration-300 rounded-full bg-cyan-500/90 backdrop-blur-sm p-4 text-white hover:bg-cyan-400 shadow-[0_0_20px_rgba(34,211,238,0.5)]"
                      >
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"></path></svg>
                      </a>
                    </div>
                  </div>

                  {/* Content Container */}
                  <div className="flex flex-1 flex-col p-8 pt-6 relative">
                    <h4 className="mb-4 text-2xl font-bold text-white group-hover:text-cyan-300 transition-colors duration-300">
                      {item.title}
                    </h4>

                    <p className="mb-8 flex-1 text-sm text-slate-300 leading-relaxed line-clamp-4 group-hover:line-clamp-none transition-all duration-300">
                      {item.desc}
                    </p>

                    <div className="mt-auto">
                      {/* Tech Stack Tags */}
                      <div className="flex flex-wrap gap-2 mb-6">
                        {item.techStack?.map((tech, i) => (
                          <span
                            key={i}
                            className="px-3 py-1 text-xs font-medium rounded-full bg-slate-800 text-cyan-200 border border-slate-700 group-hover:border-cyan-500/20 group-hover:bg-cyan-500/10 transition-colors duration-300"
                          >
                            {tech.trim()}
                          </span>
                        ))}
                      </div>

                      {/* Footer Actions */}
                      <div className="pt-6 border-t border-slate-700/50 flex items-center justify-between">
                        <a
                          href={item.view || item.demo || '#'}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center text-sm font-semibold text-cyan-400 hover:text-cyan-300 transition-colors"
                        >
                          View Project
                          <svg className="ml-2 w-4 h-4 transition-transform group-hover:translate-x-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}


